/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Manimal;
import model.Mdetservicio;
import model.Mservicio;

/**
 *
 * @author hp
 */
public class Vservicios extends javax.swing.JFrame {

    /**
     * Creates new form Vservicios
     */
    public Manimal manimal;
    public Mservicio mservicio;
    public Mdetservicio mdetservicio;
    DefaultTableModel model;
    
    public Vservicios() {
        initComponents();
        this.manimal = new Manimal();
        this.mservicio = new Mservicio();
        this.mdetservicio = new Mdetservicio();
        this.setTitle("Jp Vet - Servicios");
        
        cbanimal.setModel(manimal.getCombo());
        cbservicio.setModel(mservicio.getCombo());
        jTable1.getTableHeader().setReorderingAllowed(false);
        setDefaultCloseOperation(Vservicios.DISPOSE_ON_CLOSE);
        this.setExtendedState(Vservicios.MAXIMIZED_BOTH);
    }
    
    public void actualizar() {
        jTable1.setModel(getModel(this.mdetservicio.listar()));
        txtpeso.setText("");
        txtPrecio.setText("");
        TableColumnModel tc = jTable1.getColumnModel();
        
        tc.getColumn(0).setPreferredWidth(5);
        tc.getColumn(1).setPreferredWidth(50);
        tc.getColumn(2).setPreferredWidth(50);
        tc.getColumn(3).setPreferredWidth(50);
        tc.getColumn(4).setPreferredWidth(50);
        tc.getColumn(5).setPreferredWidth(50);
        tc.getColumn(6).setPreferredWidth(50);
        tc.getColumn(7).setPreferredWidth(50);
        tc.getColumn(8).setPreferredWidth(50);
       
    }
    
    public DefaultTableModel getModel(ArrayList<Mdetservicio> lista) {
        String[] titulos = {"id", "servicio", "animal", "tamaño", "genero", "pelo", "peso", "tejido", "precio"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        Object[] fila = new Object[9];
        for (Mdetservicio p : lista) {
            fila[0] = p.getId();
            fila[1] = p.getServicio();
            fila[2] = p.getAnimal();
            fila[3] = p.getTamanio();
            fila[4] = p.getGenero();
            fila[5] = p.getPelo();
            fila[6] = p.getPeso();
            fila[7] = p.getTejido();
            fila[8] = p.getPrecio();
            modelo.addRow(fila);
        }
        return modelo;
    }
    
    public void getData(Integer fila) {
        if (fila == -1) {
            return;
        }
        int id = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        String servicio = (String) jTable1.getValueAt(fila, 1);
        String animal = (String) jTable1.getValueAt(fila, 2);
        String tamanio = (String) jTable1.getValueAt(fila, 2);
        String genero = (String) jTable1.getValueAt(fila, 2);
        String pelo = (String) jTable1.getValueAt(fila, 2);
        double peso = Double.parseDouble(jTable1.getValueAt(fila, 2).toString());
        String tejido = (String) jTable1.getValueAt(fila, 2);
        double precio = Double.parseDouble(jTable1.getValueAt(fila, 2).toString());
        this.mdetservicio.setId(id);
        this.mdetservicio.setServicio(servicio);
        this.mdetservicio.setAnimal(animal);
        this.mdetservicio.setTamanio(tamanio);
        this.mdetservicio.setGenero(genero);
        this.mdetservicio.setPelo(pelo);
        this.mdetservicio.setPeso(peso);
        this.mdetservicio.setTejido(tejido);
        this.mdetservicio.setPrecio(precio);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbservicio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbanimal = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbtamanio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtpeso = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        cbtejido = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbpelo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbgenero = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        btregistrar = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gestionar Servicios");

        jLabel2.setText("usuario:");

        jLabel3.setText("invitado");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Servicio");

        cbservicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Animal");

        cbanimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Tamaño");

        cbtamanio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pequeño", "mediano", "grande", "gigante" }));

        jLabel9.setText("Peso");

        txtpeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLabel8.setText("Tejido");

        cbtejido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grueso", "blando" }));

        jLabel7.setText("Pelo");

        cbpelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "corto", "largo" }));

        jLabel11.setText("Genero");

        cbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "macho", "hembra" }));

        jLabel12.setText("Precio");

        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        btregistrar.setText("registrar");

        btmodificar.setText("modificar");

        bteliminar.setText("eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(cbservicio, 0, 134, Short.MAX_VALUE)
                            .addComponent(cbpelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btregistrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(bteliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbtejido, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbanimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtpeso, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbtamanio, javax.swing.GroupLayout.Alignment.LEADING, 0, 119, Short.MAX_VALUE))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addComponent(txtPrecio)
                                    .addComponent(cbgenero, 0, 73, Short.MAX_VALUE))
                                .addContainerGap(20, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(53, 53, 53))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbpelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtejido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btregistrar)
                    .addComponent(btmodificar)
                    .addComponent(bteliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("Precios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bteliminar;
    public javax.swing.JButton btmodificar;
    public javax.swing.JButton btregistrar;
    public javax.swing.JComboBox<String> cbanimal;
    public javax.swing.JComboBox<String> cbgenero;
    public javax.swing.JComboBox<String> cbpelo;
    public javax.swing.JComboBox<String> cbservicio;
    public javax.swing.JComboBox<String> cbtamanio;
    public javax.swing.JComboBox<String> cbtejido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JFormattedTextField txtPrecio;
    public javax.swing.JFormattedTextField txtpeso;
    // End of variables declaration//GEN-END:variables
}
